---
- hosts: guam
  remote_user: root
  tasks:

  - name: Install EPEL Repo - Centos/RHEL 6
    yum: 
      name: http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      state: present
  

  - name: Install list of packages
    yum: name={{item}} state=installed
    with_items:
      - php 
      - php-pear
      - mysql-server
      - php-mcrypt
      - php-mssql
      - php-tcpdf
      - php-mysql
      - php-gd
      - mod_ssl
      - php-pecl-zendopcache
      - npm
      - nodejs
      - php-soap
      - php-pclzip

#eva deps

  - get_url:
      url: https://github.com/ValidUSA/legacy-dep/raw/master/Legacy/propel.tar.gz
      dest: /root/

  - unarchive:
      src: https://github.com/ValidUSA/legacy-dep/raw/master/Legacy/propel.tar.gz
      dest: /usr/share/pear/
      remote_src: True

  - name: upgrade all pkgs
    yum:
     name: '*'
     state: latest

  - name: pearplex
    yum:
      name: https://github.com/ValidUSA/legacy-dep/raw/master/Legacy/php5-pear-channel-pearplex-1.0-1.1.noarch.rpm
      state: present
      disable_gpg_check: yes

  - name: phpexcel
    yum:
      name: https://github.com/ValidUSA/legacy-dep/raw/master/Legacy/php5-pear-phpexcel-1.7.8-2.1.noarch.rpm

  - name: install grunt
    npm:
      name: grunt-cli
      global: yes

##service changes
  - service: 
      name: mysqld
      enabled: yes

  - service:
      name: mysqld
      state: started
      
###file permessions
  - file:
      path: /usr/share/pear/propel
      owner: root
      group: root
      recurse: yes
  
  - name: Creates dir
    file: path=/etc/pki/httpd state=directory

  - copy:
      src: /home/carys/Downloads/weblinkid.com.cert
      dest: /etc/pki/httpd/ 
      owner: root
      group: root
      mode: 0600
  - copy:
      src: /home/carys/Downloads/weblinkid.com.key
      dest: /etc/pki/httpd/
      owner: root
      group: root
      mode: 0600
 
