---

- name: download epel
  get_url:
  url: http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  dest: /tmp/epel-release-6-8.noarch.rpm

- name: Install EPEL Repo - Centos/RHEL 6
  command: rpm -ivh /tmp/epel-release-6-8.noarch.rpm
  

- name: Install list of packages
  yum: name={{item}} state=installed
  with_items:
        - php 
        - php-pear
        - php-pecl
        - mysql-server
        - ntp
        - php-mcrypt
        - php-mssql
        - php-tcpdf
        - php-mysql
        - php-gd
        - mod_ssl
        - PHPExcel
        - php-pecl-zendopcache
        - npm
        - nodejs
        - php-soap
        - php-pclzip
        - php-myadmin

-copy:
  src:   
        
